import type { MetadataRoute } from 'next';

/**
 * Web app manifest — makes localmode.ai installable as an offline-capable PWA
 * (paired with the Serwist service worker in sw.ts + scripts/build-sw.mjs). Icons
 * are generated by scripts/generate-pwa-icons.mjs from the black CloudOff mark.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: 'LocalMode UI — Local-First AI',
    short_name: 'LocalMode',
    description:
      'Copy-owned AI UI components and installable blocks that run real models entirely in your browser. No servers, no API keys, data never leaves your device.',
    id: '/',
    start_url: '/',
    scope: '/',
    display: 'standalone',
    background_color: '#0a0a0a',
    theme_color: '#0a0a0a',
    categories: ['developer', 'productivity', 'utilities'],
    icons: [
      { src: '/icons/icon-192x192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
      { src: '/icons/icon-512x512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
      {
        src: '/icons/icon-512x512-maskable.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
    shortcuts: [
      { name: 'Blocks gallery', url: '/blocks' },
      { name: 'Components', url: '/docs/components' },
      { name: 'Docs', url: '/docs' },
    ],
  };
}
