import {
  MessageSquare,
  FileText,
  Image as ImageIcon,
  Mic,
  Camera,
  Search,
  Mail,
  Languages,
  FileSearch,
  Bot,
  Sparkles,
  ScanText,
  Receipt,
  Eye,
  Wand2,
  Headphones,
  Copy,
  Users,
  Lock,
  Heart,
  Zap,
  Shield,
} from 'lucide-react';
import { AppMetadata, CATEGORIES, ROUTES } from './types';

/**
 * Popular model configurations
 */
export const MODELS = {
  EMBEDDING_MINI: 'Xenova/all-MiniLM-L6-v2',
  EMBEDDING_MULTILINGUAL: 'Xenova/paraphrase-multilingual-MiniLM-L12-v2',
  SENTIMENT: 'Xenova/distilbert-base-uncased-finetuned-sst-2-english',
  ZERO_SHOT: 'Xenova/bart-large-mnli',
  NER_BASE: 'Xenova/bert-base-NER',
  RERANKER: 'Xenova/ms-marco-MiniLM-L-6-v2',
  WHISPER_TINY: 'Xenova/whisper-tiny',
  WHISPER_SMALL: 'Xenova/whisper-small',
  TTS_SPEECHT5: 'Xenova/speecht5_tts',
  VIT_BASE: 'Xenova/vit-base-patch16-224',
  CLIP_BASE: 'Xenova/clip-vit-base-patch32',
  BLIP_CAPTION: 'Xenova/blip-image-captioning-base',
  SEGFORMER: 'Xenova/segformer-b0-finetuned-ade-512-512',
  DETR: 'Xenova/detr-resnet-50',
  OPUS_EN_DE: 'Xenova/opus-mt-en-de',
  OPUS_EN_FR: 'Xenova/opus-mt-en-fr',
  OPUS_EN_ES: 'Xenova/opus-mt-en-es',
  BART_CNN: 'Xenova/bart-large-cnn',
  DISTILBERT_SQUAD: 'Xenova/distilbert-base-cased-distilled-squad',
  BERT_BASE: 'Xenova/bert-base-uncased',
  TROCR_BASE: 'Xenova/trocr-base-handwritten',
  LLAMA_1B: 'Llama-3.2-1B-Instruct-q4f16_1-MLC',
  PHI_3_5: 'Phi-3.5-mini-instruct-q4f16_1-MLC',
} as const;

export const MODEL_SIZES: Record<string, string> = {
  [MODELS.EMBEDDING_MINI]: '22MB',
  [MODELS.SENTIMENT]: '67MB',
  [MODELS.WHISPER_TINY]: '70MB',
  [MODELS.CLIP_BASE]: '150MB',
  [MODELS.BLIP_CAPTION]: '250MB',
  [MODELS.LLAMA_1B]: '712MB',
  [MODELS.PHI_3_5]: '2.1GB',
};

/**
 * All applications in the showcase
 */
export const apps: AppMetadata[] = [
  // Released Apps
  {
    id: 'llm-chat',
    title: 'LLM Chat',
    description: 'Privacy-first AI chat with streaming responses. All processing happens locally.',
    icon: MessageSquare,
    category: CATEGORIES.CHAT,
    modelSize: '78MB - 4.4GB',
    route: ROUTES.LLM_CHAT,
    priority: 'P1',
    features: ['Streaming', 'Multiple Models', 'Offline Support', 'WebGPU Accelerated'],
    models: [MODELS.LLAMA_1B],
  },
  {
    id: 'pdf-search',
    title: 'PDF Search',
    description: 'Ask questions about your PDF documents with semantic search and reranking.',
    icon: FileText,
    category: CATEGORIES.RAG,
    modelSize: '22MB + 22MB',
    route: ROUTES.PDF_SEARCH,
    priority: 'P1',
    features: ['PDF Upload', 'RAG Pipeline', 'Source Citations', 'Multi-PDF'],
    models: [MODELS.EMBEDDING_MINI, MODELS.RERANKER, MODELS.LLAMA_1B],
  },
  {
    id: 'voice-notes',
    title: 'Voice Notes & Transcription',
    description: 'Record audio and transcribe with Whisper. Search your voice notes semantically.',
    icon: Mic,
    category: CATEGORIES.AUDIO,
    modelSize: MODEL_SIZES[MODELS.WHISPER_TINY],
    route: ROUTES.VOICE_NOTES,
    priority: 'P1',
    features: ['Audio Recording', 'Transcription', 'Timestamps', 'Semantic Search'],
    models: [MODELS.WHISPER_TINY, MODELS.EMBEDDING_MINI],
    comingSoon: true,
  },
  // Coming Soon Apps
  {
    id: 'sentiment-analyzer',
    title: 'Customer Feedback Analyzer',
    description: 'Analyze sentiment of reviews and feedback. Batch process thousands of texts.',
    icon: Heart,
    category: CATEGORIES.TEXT_NLP,
    modelSize: MODEL_SIZES[MODELS.SENTIMENT],
    route: ROUTES.SENTIMENT_ANALYZER,
    priority: 'P1',
    features: ['Sentiment Analysis', 'Batch Processing', 'Statistics Dashboard', 'CSV Export'],
    models: [MODELS.SENTIMENT],
    comingSoon: true,
  },
  {
    id: 'background-remover',
    title: 'Image Background Remover',
    description: 'Remove backgrounds from images automatically. Download as PNG with transparency.',
    icon: ImageIcon,
    category: CATEGORIES.VISION,
    modelSize: '15MB',
    route: ROUTES.BACKGROUND_REMOVER,
    priority: 'P1',
    features: ['Background Removal', 'Before/After Preview', 'Batch Processing', 'PNG Export'],
    models: [MODELS.SEGFORMER],
    comingSoon: true,
  },
  {
    id: 'smart-gallery',
    title: 'Smart Photo Gallery',
    description: 'Auto-categorize photos, search by description, find similar images.',
    icon: Camera,
    category: CATEGORIES.VISION,
    modelSize: MODEL_SIZES[MODELS.CLIP_BASE],
    route: ROUTES.SMART_GALLERY,
    priority: 'P1',
    features: ['Auto-Categorization', 'Visual Search', 'Duplicate Detection', 'Batch Organize'],
    models: [MODELS.CLIP_BASE],
    comingSoon: true,
  },
  {
    id: 'document-redactor',
    title: 'Privacy Document Redactor',
    description: 'Detect and redact PII (names, locations, organizations) from documents.',
    icon: Shield,
    category: CATEGORIES.PRIVACY,
    modelSize: '110MB',
    route: ROUTES.DOCUMENT_REDACTOR,
    priority: 'P1',
    features: ['PII Detection', 'Auto-Redaction', 'Preview', 'Export Redacted'],
    models: [MODELS.NER_BASE],
    comingSoon: true,
  },
  {
    id: 'semantic-search',
    title: 'Personal Knowledge Base',
    description: 'Build your personal knowledge base with semantic and hybrid search.',
    icon: Search,
    category: CATEGORIES.RAG,
    modelSize: MODEL_SIZES[MODELS.EMBEDDING_MINI],
    route: ROUTES.SEMANTIC_SEARCH,
    priority: 'P0',
    features: ['Semantic Search', 'Hybrid Search', 'Tags', 'Related Notes'],
    models: [MODELS.EMBEDDING_MINI],
    comingSoon: true,
  },
  {
    id: 'product-search',
    title: 'E-commerce Visual Search',
    description: 'Search products by image, find similar items, auto-categorize catalog.',
    icon: Zap,
    category: CATEGORIES.VISION,
    modelSize: MODEL_SIZES[MODELS.CLIP_BASE],
    route: ROUTES.PRODUCT_SEARCH,
    priority: 'P1',
    features: ['Visual Search', 'Auto-Categorization', 'Similar Products', 'Duplicate Detection'],
    models: [MODELS.CLIP_BASE],
    comingSoon: true,
  },
  {
    id: 'meeting-assistant',
    title: 'Meeting Transcription Assistant',
    description: 'Transcribe meetings, generate summaries, extract action items.',
    icon: Users,
    category: CATEGORIES.AUDIO,
    modelSize: '240MB',
    route: ROUTES.MEETING_ASSISTANT,
    priority: 'P1',
    features: ['Transcription', 'Summarization', 'Action Items', 'Export SRT/VTT'],
    models: [MODELS.WHISPER_SMALL, MODELS.BART_CNN],
    comingSoon: true,
  },
  {
    id: 'email-classifier',
    title: 'Email Intent Classifier',
    description: 'Classify emails by intent with custom labels. Route to folders automatically.',
    icon: Mail,
    category: CATEGORIES.TEXT_NLP,
    modelSize: '400MB',
    route: ROUTES.EMAIL_CLASSIFIER,
    priority: 'P1',
    features: ['Zero-Shot Classification', 'Custom Labels', 'Batch Processing', 'Export'],
    models: [MODELS.ZERO_SHOT],
    comingSoon: true,
  },
  {
    id: 'image-captioner',
    title: 'Accessibility Alt-Text Generator',
    description: 'Generate alt-text for images automatically. Ask questions about images.',
    icon: Eye,
    category: CATEGORIES.VISION,
    modelSize: MODEL_SIZES[MODELS.BLIP_CAPTION],
    route: ROUTES.IMAGE_CAPTIONER,
    priority: 'P1',
    features: ['Image Captioning', 'Visual QA', 'Batch Processing', 'HTML Export'],
    models: [MODELS.BLIP_CAPTION],
    comingSoon: true,
  },
  {
    id: 'translator',
    title: 'Offline Translator',
    description: 'Translate text between 20+ languages. Works completely offline.',
    icon: Languages,
    category: CATEGORIES.TEXT_NLP,
    modelSize: '100-300MB',
    route: ROUTES.TRANSLATOR,
    priority: 'P2',
    features: ['20+ Languages', 'Auto-Detection', 'Batch Translation', 'History'],
    models: [MODELS.OPUS_EN_DE, MODELS.OPUS_EN_FR, MODELS.OPUS_EN_ES],
    comingSoon: true,
  },
  {
    id: 'text-summarizer',
    title: 'Document Summarizer',
    description: 'Summarize long documents into key points. Extractive and abstractive modes.',
    icon: FileSearch,
    category: CATEGORIES.TEXT_NLP,
    modelSize: '400MB',
    route: ROUTES.TEXT_SUMMARIZER,
    priority: 'P2',
    features: ['Summarization', 'Key Points', 'Length Control', 'Multi-Document'],
    models: [MODELS.BART_CNN],
    comingSoon: true,
  },
  {
    id: 'qa-bot',
    title: 'Document Q&A Bot',
    description: 'Ask questions about documents and get precise answers with confidence scores.',
    icon: Bot,
    category: CATEGORIES.TEXT_NLP,
    modelSize: '100MB',
    route: ROUTES.QA_BOT,
    priority: 'P2',
    features: ['Extractive QA', 'Confidence Scores', 'Answer Location', 'Multi-Document'],
    models: [MODELS.DISTILBERT_SQUAD],
    comingSoon: true,
  },
  {
    id: 'smart-autocomplete',
    title: 'Smart Autocomplete',
    description: 'Intelligent text completion using fill-mask models. Writing assistant.',
    icon: Sparkles,
    category: CATEGORIES.TEXT_NLP,
    modelSize: '67MB',
    route: ROUTES.SMART_AUTOCOMPLETE,
    priority: 'P2',
    features: ['Text Completion', 'Context-Aware', 'Multiple Suggestions', 'Real-Time'],
    models: [MODELS.BERT_BASE],
    comingSoon: true,
  },
  {
    id: 'ocr-scanner',
    title: 'OCR Document Scanner',
    description: 'Extract text from images and scanned documents. Supports handwriting.',
    icon: ScanText,
    category: CATEGORIES.VISION,
    modelSize: '10-50MB',
    route: ROUTES.OCR_SCANNER,
    priority: 'P2',
    features: ['Text Extraction', 'Handwriting Support', 'Multi-Language', 'PDF Generation'],
    models: [MODELS.TROCR_BASE],
    comingSoon: true,
  },
  {
    id: 'invoice-qa',
    title: 'Invoice Q&A Assistant',
    description:
      'Ask questions about invoices, receipts, and forms. Visual document understanding.',
    icon: Receipt,
    category: CATEGORIES.TEXT_NLP,
    modelSize: '200MB',
    route: ROUTES.INVOICE_QA,
    priority: 'P2',
    features: ['Document QA', 'Table Extraction', 'Form Understanding', 'Batch Processing'],
    models: ['Xenova/donut-base'],
    comingSoon: true,
  },
  {
    id: 'object-detector',
    title: 'Real-Time Object Detector',
    description: 'Detect and locate objects in images. Real-time webcam support.',
    icon: Eye,
    category: CATEGORIES.VISION,
    modelSize: '160MB',
    route: ROUTES.OBJECT_DETECTOR,
    priority: 'P2',
    features: ['Object Detection', 'Bounding Boxes', 'Real-Time', 'Webcam Support'],
    models: [MODELS.DETR],
    comingSoon: true,
  },
  {
    id: 'photo-enhancer',
    title: 'Photo Enhancer',
    description: 'Upscale and enhance images with super resolution. Restore old photos.',
    icon: Wand2,
    category: CATEGORIES.VISION,
    modelSize: '50MB',
    route: ROUTES.PHOTO_ENHANCER,
    priority: 'P2',
    features: ['Super Resolution', '2x/4x Upscaling', 'Photo Restoration', 'Batch Processing'],
    models: ['Xenova/swin2sr-lightweight-x2'],
    comingSoon: true,
  },
  {
    id: 'audiobook-creator',
    title: 'Audiobook Creator',
    description: 'Convert text to natural speech. Create audiobooks and podcasts.',
    icon: Headphones,
    category: CATEGORIES.AUDIO,
    modelSize: '200MB',
    route: ROUTES.AUDIOBOOK_CREATOR,
    priority: 'P2',
    features: ['Text-to-Speech', 'Natural Voice', 'Batch Processing', 'Audio Export'],
    models: [MODELS.TTS_SPEECHT5],
    comingSoon: true,
  },
  {
    id: 'duplicate-finder',
    title: 'Duplicate Photo Finder',
    description: 'Find visually similar and duplicate images. Clean up your photo library.',
    icon: Copy,
    category: CATEGORIES.VISION,
    modelSize: '150MB',
    route: ROUTES.DUPLICATE_FINDER,
    priority: 'P2',
    features: ['Visual Similarity', 'Duplicate Detection', 'Batch Scanning', 'Smart Cleanup'],
    models: ['Xenova/dinov2-base'],
    comingSoon: true,
  },
  {
    id: 'encrypted-vault',
    title: 'Encrypted Vault',
    description: 'End-to-end encrypted notes and documents. Privacy-first storage.',
    icon: Lock,
    category: CATEGORIES.PRIVACY,
    modelSize: '22MB',
    route: ROUTES.ENCRYPTED_VAULT,
    priority: 'P2',
    features: ['E2E Encryption', 'Secure Storage', 'Password Protected', 'Export Encrypted'],
    models: [MODELS.EMBEDDING_MINI],
    comingSoon: true,
  },
];
