import {
  MessageSquare,
  FileText,
  Image as ImageIcon,
  Mic,
  Camera,
  Search,
  Mail,
  Languages,
  FileSearch,
  Bot,
  Sparkles,
  ScanText,
  Receipt,
  Eye,
  Wand2,
  Headphones,
  Copy,
  Users,
  Lock,
  Heart,
  Zap,
  Shield,
  Braces,
  Link,
  Brain,
  ArrowRightLeft,
  Cpu,
  BarChart3,
} from 'lucide-react';
import { AppMetadata, CATEGORIES, ROUTES } from './types';

/**
 * Popular model configurations
 */
export const MODELS = {
  EMBEDDING_SMALL: 'Xenova/bge-small-en-v1.5',
  EMBEDDING_MULTILINGUAL: 'Xenova/paraphrase-multilingual-MiniLM-L12-v2',
  SENTIMENT: 'Xenova/distilbert-base-uncased-finetuned-sst-2-english',
  ZERO_SHOT: 'Xenova/mobilebert-uncased-mnli',
  NER_BASE: 'Xenova/bert-base-NER',
  RERANKER: 'Xenova/ms-marco-MiniLM-L-6-v2',
  MOONSHINE_TINY: 'onnx-community/moonshine-tiny-ONNX',
  MOONSHINE_BASE: 'onnx-community/moonshine-base-ONNX',
  TTS_KOKORO: 'onnx-community/Kokoro-82M-v1.0-ONNX',
  VIT_BASE: 'Xenova/vit-base-patch16-224',
  SIGLIP_BASE: 'Xenova/siglip-base-patch16-224',
  FLORENCE_2: 'onnx-community/Florence-2-base-ft',
  RMBG: 'briaai/RMBG-1.4',
  DFINE_NANO: 'onnx-community/dfine_n_coco-ONNX',
  OPUS_EN_DE: 'Xenova/opus-mt-en-de',
  OPUS_EN_FR: 'Xenova/opus-mt-en-fr',
  OPUS_EN_ES: 'Xenova/opus-mt-en-es',
  DISTILBART_CNN: 'Xenova/distilbart-cnn-6-6',
  DISTILBERT_SQUAD: 'Xenova/distilbert-base-cased-distilled-squad',
  MODERNBERT_BASE: 'onnx-community/ModernBERT-base-ONNX',
  TROCR_SMALL: 'Xenova/trocr-small-printed',
  DINOV3_SMALL: 'onnx-community/dinov3-vits16-pretrain-lvd1689m-ONNX',
  LLAMA_1B: 'Llama-3.2-1B-Instruct-q4f16_1-MLC',
  QWEN_1_5B: 'Qwen2.5-1.5B-Instruct-q4f16_1-MLC',
  QWEN3_1_7B: 'Qwen3-1.7B-q4f16_1-MLC',
  PHI_3_5: 'Phi-3.5-mini-instruct-q4f16_1-MLC',
} as const;

export const MODEL_SIZES: Record<string, string> = {
  [MODELS.EMBEDDING_SMALL]: '33MB',
  [MODELS.SENTIMENT]: '67MB',
  [MODELS.MOONSHINE_TINY]: '50MB',
  [MODELS.SIGLIP_BASE]: '400MB',
  [MODELS.FLORENCE_2]: '460MB',
  [MODELS.LLAMA_1B]: '712MB',
  [MODELS.QWEN_1_5B]: '1.0GB',
  [MODELS.QWEN3_1_7B]: '1.1GB',
  [MODELS.PHI_3_5]: '2.1GB',
};

/**
 * All applications in the showcase
 */
export const apps: AppMetadata[] = [
  // Released Apps
  {
    id: 'llm-chat',
    title: 'LLM Chat',
    description: 'Privacy-first AI chat with streaming responses and vision support. All processing happens locally.',
    icon: MessageSquare,
    category: CATEGORIES.CHAT,
    modelSize: '78MB - 4.4GB',
    route: ROUTES.LLM_CHAT,
    features: ['Streaming', 'Multiple Models', 'Vision (Image Input)', 'Offline Support', 'WebGPU Accelerated'],
    models: [MODELS.LLAMA_1B],
  },
  {
    id: 'pdf-search',
    title: 'PDF Search',
    description: 'Ask questions about your PDF documents with semantic search and reranking.',
    icon: FileText,
    category: CATEGORIES.RAG,
    modelSize: '33MB + 22MB',
    route: ROUTES.PDF_SEARCH,
    features: ['PDF Upload', 'RAG Pipeline', 'Source Citations', 'Multi-PDF'],
    models: [MODELS.EMBEDDING_SMALL, MODELS.RERANKER, MODELS.LLAMA_1B],
  },
  {
    id: 'voice-notes',
    title: 'Voice Notes & Transcription',
    description: 'Record audio and transcribe with Moonshine. Search your voice notes semantically.',
    icon: Mic,
    category: CATEGORIES.AUDIO,
    modelSize: MODEL_SIZES[MODELS.MOONSHINE_TINY],
    route: ROUTES.VOICE_NOTES,
    features: ['Audio Recording', 'Transcription', 'Timestamps', 'Semantic Search'],
    models: [MODELS.MOONSHINE_TINY, MODELS.EMBEDDING_SMALL],
  },
  {
    id: 'sentiment-analyzer',
    title: 'Customer Feedback Analyzer',
    description: 'Analyze sentiment of reviews and feedback. Batch process thousands of texts.',
    icon: Heart,
    category: CATEGORIES.TEXT_NLP,
    modelSize: MODEL_SIZES[MODELS.SENTIMENT],
    route: ROUTES.SENTIMENT_ANALYZER,
    features: ['Sentiment Analysis', 'Batch Processing', 'Statistics Dashboard', 'CSV Export'],
    models: [MODELS.SENTIMENT],
  },
  {
    id: 'background-remover',
    title: 'Image Background Remover',
    description: 'Remove backgrounds from images automatically. Download as PNG with transparency.',
    icon: ImageIcon,
    category: CATEGORIES.VISION,
    modelSize: '170MB',
    route: ROUTES.BACKGROUND_REMOVER,
    features: ['Background Removal', 'Before/After Preview', 'Batch Processing', 'PNG Export'],
    models: [MODELS.RMBG],
  },
  {
    id: 'smart-gallery',
    title: 'Smart Photo Gallery',
    description: 'Auto-categorize photos, search by description, find similar images.',
    icon: Camera,
    category: CATEGORIES.VISION,
    modelSize: MODEL_SIZES[MODELS.SIGLIP_BASE],
    route: ROUTES.SMART_GALLERY,
    features: ['Auto-Categorization', 'Visual Search', 'Duplicate Detection', 'Batch Organize'],
    models: [MODELS.SIGLIP_BASE],
  },
  {
    id: 'document-redactor',
    title: 'Privacy Document Redactor',
    description: 'Detect and redact PII (names, locations, organizations) from documents.',
    icon: Shield,
    category: CATEGORIES.PRIVACY,
    modelSize: '110MB',
    route: ROUTES.DOCUMENT_REDACTOR,
    features: ['PII Detection', 'Auto-Redaction', 'Preview', 'Export Redacted'],
    models: [MODELS.NER_BASE],
  },
  {
    id: 'semantic-search',
    title: 'Personal Knowledge Base',
    description: 'Build your personal knowledge base with semantic and hybrid search.',
    icon: Search,
    category: CATEGORIES.RAG,
    modelSize: MODEL_SIZES[MODELS.EMBEDDING_SMALL],
    route: ROUTES.SEMANTIC_SEARCH,
    features: ['Semantic Search', 'Hybrid Search', 'Tags', 'Related Notes'],
    models: [MODELS.EMBEDDING_SMALL],
  },
  {
    id: 'product-search',
    title: 'E-commerce Visual Search',
    description: 'Search products by image, find similar items, auto-categorize catalog.',
    icon: Zap,
    category: CATEGORIES.VISION,
    modelSize: MODEL_SIZES[MODELS.SIGLIP_BASE],
    route: ROUTES.PRODUCT_SEARCH,
    features: ['Visual Search', 'Auto-Categorization', 'Similar Products', 'Duplicate Detection'],
    models: [MODELS.SIGLIP_BASE],
  },
  {
    id: 'meeting-assistant',
    title: 'Meeting Transcription Assistant',
    description: 'Transcribe meetings, generate summaries, extract action items.',
    icon: Users,
    category: CATEGORIES.AUDIO,
    modelSize: '437MB',
    route: ROUTES.MEETING_ASSISTANT,
    features: ['Transcription', 'Summarization', 'Action Items', 'Export SRT/VTT'],
    models: [MODELS.MOONSHINE_BASE, MODELS.DISTILBART_CNN],
  },
  {
    id: 'email-classifier',
    title: 'Email Intent Classifier',
    description: 'Classify emails by intent with custom labels. Route to folders automatically.',
    icon: Mail,
    category: CATEGORIES.TEXT_NLP,
    modelSize: '400MB',
    route: ROUTES.EMAIL_CLASSIFIER,
    features: ['Zero-Shot Classification', 'Custom Labels', 'Batch Processing', 'Export'],
    models: [MODELS.ZERO_SHOT],
  },
  {
    id: 'image-captioner',
    title: 'Accessibility Alt-Text Generator',
    description: 'Generate alt-text for images automatically. Ask questions about images.',
    icon: Eye,
    category: CATEGORIES.VISION,
    modelSize: MODEL_SIZES[MODELS.FLORENCE_2],
    route: ROUTES.IMAGE_CAPTIONER,
    features: ['Image Captioning', 'Visual QA', 'Batch Processing', 'HTML Export'],
    models: [MODELS.FLORENCE_2],
  },
  {
    id: 'translator',
    title: 'Offline Translator',
    description: 'Translate text between 20+ languages. Works completely offline.',
    icon: Languages,
    category: CATEGORIES.TEXT_NLP,
    modelSize: '100-300MB',
    route: ROUTES.TRANSLATOR,
    features: ['20+ Languages', 'Auto-Detection', 'Batch Translation', 'History'],
    models: [MODELS.OPUS_EN_DE, MODELS.OPUS_EN_FR, MODELS.OPUS_EN_ES],
  },
  {
    id: 'text-summarizer',
    title: 'Document Summarizer',
    description: 'Summarize long documents into key points. Extractive and abstractive modes.',
    icon: FileSearch,
    category: CATEGORIES.TEXT_NLP,
    modelSize: '200MB',
    route: ROUTES.TEXT_SUMMARIZER,
    features: ['Summarization', 'Key Points', 'Length Control', 'Multi-Document'],
    models: [MODELS.DISTILBART_CNN],
  },
  {
    id: 'qa-bot',
    title: 'Document Q&A Bot',
    description: 'Ask questions about documents and get precise answers with confidence scores.',
    icon: Bot,
    category: CATEGORIES.TEXT_NLP,
    modelSize: '100MB',
    route: ROUTES.QA_BOT,
    features: ['Extractive QA', 'Confidence Scores', 'Answer Location', 'Multi-Document'],
    models: [MODELS.DISTILBERT_SQUAD],
  },
  {
    id: 'smart-autocomplete',
    title: 'Smart Autocomplete',
    description: 'Intelligent text completion using fill-mask models. Writing assistant.',
    icon: Sparkles,
    category: CATEGORIES.TEXT_NLP,
    modelSize: '150MB',
    route: ROUTES.SMART_AUTOCOMPLETE,
    features: ['Text Completion', 'Context-Aware', 'Multiple Suggestions', 'Real-Time'],
    models: [MODELS.MODERNBERT_BASE],
  },
  {
    id: 'ocr-scanner',
    title: 'OCR Document Scanner',
    description: 'Extract text from images and scanned documents. Supports handwriting.',
    icon: ScanText,
    category: CATEGORIES.VISION,
    modelSize: '10-50MB',
    route: ROUTES.OCR_SCANNER,
    features: ['Text Extraction', 'Handwriting Support', 'Multi-Language', 'PDF Generation'],
    models: [MODELS.TROCR_SMALL],
  },
  {
    id: 'invoice-qa',
    title: 'Invoice Q&A Assistant',
    description:
      'Ask questions about invoices, receipts, and forms. Visual document understanding.',
    icon: Receipt,
    category: CATEGORIES.TEXT_NLP,
    modelSize: '460MB',
    route: ROUTES.INVOICE_QA,
    features: ['Document QA', 'Table Extraction', 'Form Understanding', 'Batch Processing'],
    models: [MODELS.FLORENCE_2],
  },
  {
    id: 'object-detector',
    title: 'Real-Time Object Detector',
    description: 'Detect and locate objects in images. Real-time webcam support.',
    icon: Eye,
    category: CATEGORIES.VISION,
    modelSize: '130MB',
    route: ROUTES.OBJECT_DETECTOR,
    features: ['Object Detection', 'Bounding Boxes', 'Real-Time', 'Webcam Support'],
    models: [MODELS.DFINE_NANO],
  },
  {
    id: 'photo-enhancer',
    title: 'Photo Enhancer',
    description: 'Upscale and enhance images with super resolution. Restore old photos.',
    icon: Wand2,
    category: CATEGORIES.VISION,
    modelSize: '50MB',
    route: ROUTES.PHOTO_ENHANCER,
    features: ['Super Resolution', '2x/4x Upscaling', 'Photo Restoration', 'Batch Processing'],
    models: ['Xenova/swin2SR-lightweight-x2-64'],
  },
  {
    id: 'audiobook-creator',
    title: 'Audiobook Creator',
    description: 'Convert text to natural speech. Create audiobooks and podcasts.',
    icon: Headphones,
    category: CATEGORIES.AUDIO,
    modelSize: '30MB',
    route: ROUTES.AUDIOBOOK_CREATOR,
    features: ['Text-to-Speech', 'Natural Voice', 'Batch Processing', 'Audio Export'],
    models: ['Xenova/mms-tts-eng'],
  },
  {
    id: 'duplicate-finder',
    title: 'Duplicate Photo Finder',
    description: 'Find visually similar and duplicate images. Clean up your photo library.',
    icon: Copy,
    category: CATEGORIES.VISION,
    modelSize: '86MB',
    route: ROUTES.DUPLICATE_FINDER,
    features: ['Visual Similarity', 'Duplicate Detection', 'Batch Scanning', 'Smart Cleanup'],
    models: [MODELS.DINOV3_SMALL],
  },
  {
    id: 'encrypted-vault',
    title: 'Encrypted Vault',
    description: 'End-to-end encrypted notes and documents. Privacy-first storage.',
    icon: Lock,
    category: CATEGORIES.PRIVACY,
    modelSize: '33MB',
    route: ROUTES.ENCRYPTED_VAULT,
    features: ['E2E Encryption', 'Secure Storage', 'Password Protected', 'Export Encrypted'],
    models: [MODELS.EMBEDDING_SMALL],
  },
  {
    id: 'smart-writer',
    title: 'Smart Writer',
    description: 'AI writing assistant with summarization and translation. Instant with Chrome AI, automatic fallback to Transformers.js.',
    icon: Zap,
    category: CATEGORIES.TEXT_NLP,
    modelSize: '0MB (Chrome AI) / 300MB (fallback)',
    route: ROUTES.SMART_WRITER,
    features: ['Summarization', 'Translation', 'Chrome AI', 'Auto-Fallback'],
    models: [MODELS.DISTILBART_CNN],
  },
  {
    id: 'data-extractor',
    title: 'Data Extractor',
    description: 'Extract structured JSON from text using local LLMs. Schema-validated, retry with self-correction.',
    icon: Braces,
    category: CATEGORIES.TEXT_NLP,
    modelSize: '1.1GB',
    route: ROUTES.DATA_EXTRACTOR,
    features: ['Structured Output', 'JSON Schema', 'Template-Based', 'Model Selection'],
    models: ['Qwen3-1.7B-q4f16_1-MLC'],
  },
  {
    id: 'langchain-rag',
    title: 'LangChain RAG',
    description: 'Full LangChain RAG pipeline running locally. Document ingestion, semantic search, and LLM answers with source citations.',
    icon: Link,
    category: CATEGORIES.RAG,
    modelSize: '33MB + 1.1GB',
    route: ROUTES.LANGCHAIN_RAG,
    features: ['LangChain Compatible', 'RAG Pipeline', 'Local LLM', 'Source Citations'],
    models: [MODELS.EMBEDDING_SMALL, MODELS.QWEN3_1_7B],
  },
  {
    id: 'cross-modal-search',
    title: 'Cross-Modal Photo Search',
    description: 'Search photos by text description or reference image. CLIP embeds text and images in the same vector space.',
    icon: Search,
    category: CATEGORIES.VISION,
    modelSize: '~350MB',
    route: ROUTES.CROSS_MODAL_SEARCH,
    features: ['Text-to-Image Search', 'Image-to-Image Search', 'CLIP Embeddings', 'Drag & Drop Upload'],
    models: ['Xenova/clip-vit-base-patch32'],
  },
  {
    id: 'research-agent',
    title: 'Research Agent',
    description: 'AI agent that uses tools to research topics step-by-step. Watch reasoning unfold in real-time.',
    icon: Brain,
    category: CATEGORIES.CHAT,
    modelSize: MODEL_SIZES[MODELS.QWEN3_1_7B],
    route: ROUTES.RESEARCH_AGENT,
    features: ['ReAct Reasoning', 'Tool Calling', 'Step Visualization', 'Offline Agent'],
    models: [MODELS.QWEN3_1_7B],
  },
  {
    id: 'data-migrator',
    title: 'Data Migrator',
    description: 'Import vectors from Pinecone, ChromaDB, CSV, or JSONL. Export to interoperable formats. Re-embed text-only records locally.',
    icon: ArrowRightLeft,
    category: CATEGORIES.RAG,
    modelSize: MODEL_SIZES[MODELS.EMBEDDING_SMALL],
    route: ROUTES.DATA_MIGRATOR,
    features: ['Format Auto-Detection', 'Import Preview', 'Re-embedding', 'CSV & JSONL Export'],
    models: [MODELS.EMBEDDING_SMALL],
  },
  {
    id: 'gguf-explorer',
    title: 'GGUF Explorer',
    description: 'Inspect GGUF model metadata, check browser compatibility, and chat via WASM. Access 135K+ models from HuggingFace.',
    icon: Cpu,
    category: CATEGORIES.CHAT,
    modelSize: '105MB - 4.9GB',
    route: ROUTES.GGUF_EXPLORER,
    features: ['GGUF Inspection', 'Browser Compat Check', 'WASM Inference', '135K+ Models'],
    models: ['bartowski/Llama-3.2-1B-Instruct-GGUF:Llama-3.2-1B-Instruct-Q4_K_M.gguf'],
  },
  {
    id: 'model-advisor',
    title: 'Model Advisor',
    description: 'Detect device capabilities, get ranked model recommendations, and compute optimal batch sizes. No model download required.',
    icon: Cpu,
    category: CATEGORIES.TEXT_NLP,
    modelSize: '0MB',
    route: ROUTES.MODEL_ADVISOR,
    features: ['Device Detection', 'Model Recommendations', 'Adaptive Batching', 'Custom Registry'],
    models: [],
  },
  {
    id: 'model-evaluator',
    title: 'Model Evaluator',
    description: 'Evaluate classification models with accuracy, precision, recall, F1, and confusion matrix. Calibrate similarity thresholds from corpus embeddings.',
    icon: BarChart3,
    category: CATEGORIES.TEXT_NLP,
    modelSize: '67MB',
    route: ROUTES.MODEL_EVALUATOR,
    features: ['Model Evaluation', 'Confusion Matrix', 'Threshold Calibration', 'JSON Export'],
    models: [MODELS.SENTIMENT],
  },
];
