'use client';

/**
 * @file artifact-demo.tsx
 * @description Demo for the Artifact docked-canvas shell, used by the docs live
 * preview. Drives the canvas content from a REAL local `useGenerateText` run
 * (no mock): click "Generate" to download/load a small local model and render
 * its output in the docked panel. The copy / download / refresh / close toolbar
 * actions all operate entirely client-side.
 */

import { useState } from 'react';
import { useGenerateText } from '@localmode/react';
import { transformers } from '@localmode/transformers';
import {
  Artifact,
  ArtifactHeader,
  ArtifactTitle,
  ArtifactDescription,
  ArtifactActions,
  ArtifactAction,
  ArtifactClose,
  ArtifactContent,
} from './artifact';

const PROMPT =
  'Write a short TypeScript function `slugify(input: string): string`. Reply with only the code.';

export default function ArtifactDemo() {
  const [open, setOpen] = useState(true);
  const model = transformers.languageModel('onnx-community/granite-4.0-350m-ONNX-web');
  const { data, isLoading, error, execute } = useGenerateText({
    model,
    maxTokens: 200,
  });

  const content = data?.text ?? '';

  return (
    <div className="flex w-full min-w-0 max-w-md flex-col gap-3">
      <div className="flex items-center gap-2">
        <button
          type="button"
          onClick={() => execute(PROMPT)}
          disabled={isLoading}
          className="inline-flex h-8 items-center rounded-md bg-primary px-3 text-sm font-medium text-primary-foreground hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-[3px] focus-visible:ring-ring/50 disabled:opacity-50"
        >
          {isLoading ? 'Generating…' : 'Generate'}
        </button>
        {!open && (
          <button
            type="button"
            onClick={() => setOpen(true)}
            className="inline-flex h-8 items-center rounded-md border border-border px-3 text-sm focus-visible:outline-none focus-visible:ring-[3px] focus-visible:ring-ring/50"
          >
            Reopen canvas
          </button>
        )}
      </div>

      <Artifact open={open} className="h-80 w-full min-w-0 max-w-md">
        <ArtifactHeader>
          <div className="min-w-0">
            <ArtifactTitle>slugify.ts</ArtifactTitle>
            <ArtifactDescription>
              Generated by a local model (transformers · Granite 4.0 350M)
            </ArtifactDescription>
          </div>
          <ArtifactActions>
            <ArtifactAction content={content} label="Copy" />
            <ArtifactAction
              content={content}
              fileName="slugify.ts"
              label="Download"
            />
            <ArtifactAction onClick={() => execute(PROMPT)} label="Refresh" />
            <ArtifactClose onClick={() => setOpen(false)} />
          </ArtifactActions>
        </ArtifactHeader>
        <ArtifactContent>
          {error ? (
            <p className="text-sm text-destructive">{error.message}</p>
          ) : content ? (
            <pre>{content}</pre>
          ) : (
            <p className="text-sm text-muted-foreground">
              {isLoading
                ? 'Loading the local model and generating…'
                : 'Click Generate to fill the canvas from a local model.'}
            </p>
          )}
        </ArtifactContent>
      </Artifact>
    </div>
  );
}
