'use client';

/**
 * @file sw-registrar.tsx
 * @description Registers the Serwist service worker (public/sw.js) in production
 * only — the SW is generated by the postbuild step, so it doesn't exist in dev.
 * Mounted once in the root layout.
 */
import { useEffect } from 'react';

export function SWRegistrar() {
  useEffect(() => {
    if (process.env.NODE_ENV === 'production' && 'serviceWorker' in navigator) {
      navigator.serviceWorker.register('/sw.js').catch(() => {
        // Registration is best-effort; a failure must never break the app.
      });
    }
  }, []);

  return null;
}
