/**
 * @file generate-block-source.ts
 * @description Generates static source strings for public block pages.
 *
 * Next/Turbopack warns when Server Components import helpers that read files
 * with dynamic filesystem paths. The block pages only need a Code-tab snapshot
 * of each block's implementation file, so generate a plain TypeScript object.
 *
 * Conventions (both discovered; `readBlockSource(key)` looks up either):
 *  - FLAT single-block category: `src/app/blocks/<name>/<name>.tsx` → key `<name>`.
 *  - MULTI-block category: each block lives at
 *    `src/app/blocks/<category>/<slug>/<slug>.tsx` → key `<category>/<slug>`
 *    (the key `page.tsx` passes to `readBlockSource` and `BlockShellSection`
 *    receives as its `source`). Flat and nested blocks can coexist under one
 *    category dir while an old tabbed impl is being dissolved.
 * A directory with no matching-name file (or a non-directory) is skipped, so the
 * script is safe to run before any block exists.
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

import { stripSnippet } from './strip-block-snippets';

const APP_ROOT = process.cwd();
const BLOCKS_DIR = path.join(APP_ROOT, 'src', 'app', 'blocks');
const OUT_FILE = path.join(APP_ROOT, 'src', 'lib', 'block-source.generated.ts');

const sources: Record<string, string> = {};

/** Snapshot `dir/<name>.tsx` under `key` (stripped) if the impl file exists. */
function snapshot(dir: string, name: string, key: string) {
  const impl = path.join(dir, `${name}.tsx`);
  if (existsSync(impl)) {
    // The Code-tab snapshot is shipped surface, so strip dev-only snippet noise
    // (data-testid + QA/E2E comments, trimmed header) via the same transform the
    // registry payloads use.
    sources[key] = stripSnippet(readFileSync(impl, 'utf8'));
  }
}

if (existsSync(BLOCKS_DIR)) {
  for (const entry of readdirSync(BLOCKS_DIR, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const categoryDir = path.join(BLOCKS_DIR, entry.name);
    // Flat single-block category: <name>/<name>.tsx → key "<name>".
    snapshot(categoryDir, entry.name, entry.name);
    // Multi-block category: <category>/<slug>/<slug>.tsx → key "<category>/<slug>".
    for (const sub of readdirSync(categoryDir, { withFileTypes: true })) {
      if (!sub.isDirectory()) continue;
      snapshot(path.join(categoryDir, sub.name), sub.name, `${entry.name}/${sub.name}`);
    }
  }
}

const body = `/* eslint-disable */\n// This file is generated by scripts/generate-block-source.ts.\n// Do not edit by hand.\n\nexport const blockSources: Record<string, string> = ${JSON.stringify(sources, null, 2)};\n`;

writeFileSync(OUT_FILE, body);

console.log(
  `[generate-block-source] wrote src/lib/block-source.generated.ts (${Object.keys(sources).length} block(s))`,
);
